GET http://localhost:8000/api/users
Accept: application/json

###
GET http://localhost:8000/api/questions
Accept: application/json

###
GET http://localhost:8000/api/questions/python/easy
Accept: application/json

###
GET http://localhost:8000/api/leaderboards
Accept: application/json

###
POST http://localhost:8000/api/leaderboards
Content-Type: application/json
Accept: application/json

{
  "name": "AnggaC",
    "pelajaran": "Python",
  "score": 100
}
